-- Run this in Supabase SQL editor.

create table if not exists public.theatres (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  address text not null,
  website text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.films (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer,
  tmdb_id bigint,
  ticket_link text not null default '',
  tmdb_json jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.theatre_films (
  theatre_id bigint not null references public.theatres(id) on delete cascade,
  film_id bigint not null references public.films(id) on delete cascade,
  ticket_link text not null default '',
  created_at timestamptz not null default now(),
  primary key (theatre_id, film_id)
);

create table if not exists public.showings (
  id bigint generated by default as identity primary key,
  theatre_id bigint not null references public.theatres(id) on delete cascade,
  film_id bigint not null references public.films(id) on delete cascade,
  show_date date not null,
  times text[] not null,
  created_at timestamptz not null default now()
);

alter table public.theatres enable row level security;
alter table public.films enable row level security;
alter table public.theatre_films enable row level security;
alter table public.showings enable row level security;

-- Public read access for site visitors.
drop policy if exists "Public read theatres" on public.theatres;
create policy "Public read theatres" on public.theatres
for select using (true);

drop policy if exists "Public read films" on public.films;
create policy "Public read films" on public.films
for select using (true);

drop policy if exists "Public read theatre_films" on public.theatre_films;
create policy "Public read theatre_films" on public.theatre_films
for select using (true);

drop policy if exists "Public read showings" on public.showings;
create policy "Public read showings" on public.showings
for select using (true);

-- Authenticated users can manage data (admin usage).
drop policy if exists "Auth write theatres" on public.theatres;
create policy "Auth write theatres" on public.theatres
for all to authenticated
using (true)
with check (true);

drop policy if exists "Auth write films" on public.films;
create policy "Auth write films" on public.films
for all to authenticated
using (true)
with check (true);

drop policy if exists "Auth write theatre_films" on public.theatre_films;
create policy "Auth write theatre_films" on public.theatre_films
for all to authenticated
using (true)
with check (true);

drop policy if exists "Auth write showings" on public.showings;
create policy "Auth write showings" on public.showings
for all to authenticated
using (true)
with check (true);

drop function if exists public.replace_showtimes_data(jsonb);
create or replace function public.replace_showtimes_data(
  payload jsonb,
  allow_ticket_link_clear boolean default false
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  theatre_item jsonb;
  film_item jsonb;
  theatre_film_item jsonb;
  showing_item jsonb;
  theatre_id_map jsonb := '{}'::jsonb;
  film_id_map jsonb := '{}'::jsonb;
  theatre_id bigint;
  film_id bigint;
  theatre_key text;
  film_key text;
  risky_ticket_link_clears integer := 0;
begin
  if auth.role() <> 'authenticated' then
    raise exception 'Not authorized';
  end if;

  if payload is null then
    raise exception 'Payload is required';
  end if;

  if not coalesce(allow_ticket_link_clear, false) then
    with payload_theatres as (
      select
        value->>'key' as theatre_key,
        nullif(value->>'db_id', '')::bigint as theatre_db_id,
        lower(trim(value->>'name')) as theatre_name_key,
        lower(trim(value->>'city')) as theatre_city_key
      from jsonb_array_elements(coalesce(payload->'theatres', '[]'::jsonb))
    ),
    payload_films as (
      select
        value->>'key' as film_key,
        nullif(value->>'db_id', '')::bigint as film_db_id,
        case
          when nullif(value->>'tmdb_id', '') is not null then 'tmdb:' || (nullif(value->>'tmdb_id', '')::bigint)::text
          else lower(trim(value->>'title')) || '::' || coalesce(value->>'year', '')
        end as film_identity_key
      from jsonb_array_elements(coalesce(payload->'films', '[]'::jsonb))
    ),
    payload_links as (
      select
        coalesce(nullif(link_item->>'theatre_db_id', '')::bigint, pt.theatre_db_id) as theatre_db_id,
        coalesce(nullif(link_item->>'film_db_id', '')::bigint, pf.film_db_id) as film_db_id,
        pt.theatre_name_key,
        pt.theatre_city_key,
        pf.film_identity_key,
        nullif(trim(coalesce(link_item->>'ticket_link', '')), '') as ticket_link
      from jsonb_array_elements(coalesce(payload->'theatre_films', '[]'::jsonb)) link_item
      join payload_theatres pt
        on pt.theatre_key = link_item->>'theatre_key'
      join payload_films pf
        on pf.film_key = link_item->>'film_key'
    ),
    existing_links as (
      select
        tf.theatre_id,
        tf.film_id,
        lower(trim(t.name)) as theatre_name_key,
        lower(trim(t.city)) as theatre_city_key,
        case
          when f.tmdb_id is not null then 'tmdb:' || f.tmdb_id::text
          else lower(trim(f.title)) || '::' || coalesce(f.year::text, '')
        end as film_identity_key,
        nullif(trim(tf.ticket_link), '') as ticket_link
      from public.theatre_films tf
      join public.theatres t
        on t.id = tf.theatre_id
      join public.films f
        on f.id = tf.film_id
      where nullif(trim(tf.ticket_link), '') is not null
    ),
    risky as (
      select 1
      from existing_links existing
      left join payload_links incoming
        on (
          incoming.theatre_db_id is not null
          and incoming.film_db_id is not null
          and incoming.theatre_db_id = existing.theatre_id
          and incoming.film_db_id = existing.film_id
        ) or (
          (incoming.theatre_db_id is null or incoming.film_db_id is null)
          and incoming.theatre_name_key = existing.theatre_name_key
          and incoming.theatre_city_key = existing.theatre_city_key
          and incoming.film_identity_key = existing.film_identity_key
        )
      where incoming.ticket_link is null
    )
    select count(*) into risky_ticket_link_clears from risky;

    if risky_ticket_link_clears > 0 then
      raise exception 'Blocked save: payload would clear % existing ticket link(s).', risky_ticket_link_clears;
    end if;
  end if;

  delete from public.showings where true;
  delete from public.theatre_films where true;
  delete from public.theatres where true;
  delete from public.films where true;

  for theatre_item in
    select value from jsonb_array_elements(coalesce(payload->'theatres', '[]'::jsonb))
  loop
    insert into public.theatres (name, city, address, website)
    values (
      coalesce(theatre_item->>'name', ''),
      coalesce(theatre_item->>'city', ''),
      coalesce(theatre_item->>'address', ''),
      coalesce(theatre_item->>'website', '')
    )
    returning id into theatre_id;

    theatre_key := theatre_item->>'key';
    theatre_id_map := theatre_id_map || jsonb_build_object(theatre_key, theatre_id);
  end loop;

  for film_item in
    select value from jsonb_array_elements(coalesce(payload->'films', '[]'::jsonb))
  loop
    insert into public.films (title, year, tmdb_id, ticket_link, tmdb_json)
    values (
      coalesce(film_item->>'title', ''),
      nullif(film_item->>'year', '')::integer,
      nullif(film_item->>'tmdb_id', '')::bigint,
      coalesce(film_item->>'ticket_link', ''),
      film_item->'tmdb_json'
    )
    returning id into film_id;

    film_key := film_item->>'key';
    film_id_map := film_id_map || jsonb_build_object(film_key, film_id);
  end loop;

  for theatre_film_item in
    select value from jsonb_array_elements(coalesce(payload->'theatre_films', '[]'::jsonb))
  loop
    theatre_id := nullif(theatre_id_map->>(theatre_film_item->>'theatre_key'), '')::bigint;
    film_id := nullif(film_id_map->>(theatre_film_item->>'film_key'), '')::bigint;

    if theatre_id is not null and film_id is not null then
      insert into public.theatre_films (theatre_id, film_id, ticket_link)
      values (theatre_id, film_id, coalesce(theatre_film_item->>'ticket_link', ''));
    end if;
  end loop;

  for showing_item in
    select value from jsonb_array_elements(coalesce(payload->'showings', '[]'::jsonb))
  loop
    theatre_id := nullif(theatre_id_map->>(showing_item->>'theatre_key'), '')::bigint;
    film_id := nullif(film_id_map->>(showing_item->>'film_key'), '')::bigint;

    if theatre_id is not null and film_id is not null then
      insert into public.showings (theatre_id, film_id, show_date, times)
      values (
        theatre_id,
        film_id,
        (showing_item->>'show_date')::date,
        array(select jsonb_array_elements_text(coalesce(showing_item->'times', '[]'::jsonb)))
      );
    end if;
  end loop;
end;
$$;

revoke all on function public.replace_showtimes_data(jsonb, boolean) from public;
grant execute on function public.replace_showtimes_data(jsonb, boolean) to authenticated;
