-- Run this in Supabase SQL editor.

create table if not exists public.theatres (
  id bigint generated by default as identity primary key,
  name text not null,
  city text not null,
  address text not null,
  website text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.films (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer,
  tmdb_id bigint,
  ticket_link text not null default '',
  tmdb_json jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.theatre_films (
  theatre_id bigint not null references public.theatres(id) on delete cascade,
  film_id bigint not null references public.films(id) on delete cascade,
  ticket_link text not null default '',
  created_at timestamptz not null default now(),
  primary key (theatre_id, film_id)
);

create table if not exists public.showings (
  id bigint generated by default as identity primary key,
  theatre_id bigint not null references public.theatres(id) on delete cascade,
  film_id bigint not null references public.films(id) on delete cascade,
  show_date date not null,
  times text[] not null,
  created_at timestamptz not null default now()
);

alter table public.theatres enable row level security;
alter table public.films enable row level security;
alter table public.theatre_films enable row level security;
alter table public.showings enable row level security;

-- Public read access for site visitors.
drop policy if exists "Public read theatres" on public.theatres;
create policy "Public read theatres" on public.theatres
for select using (true);

drop policy if exists "Public read films" on public.films;
create policy "Public read films" on public.films
for select using (true);

drop policy if exists "Public read theatre_films" on public.theatre_films;
create policy "Public read theatre_films" on public.theatre_films
for select using (true);

drop policy if exists "Public read showings" on public.showings;
create policy "Public read showings" on public.showings
for select using (true);

-- Authenticated users can manage data (admin usage).
drop policy if exists "Auth write theatres" on public.theatres;
create policy "Auth write theatres" on public.theatres
for all to authenticated
using (true)
with check (true);

drop policy if exists "Auth write films" on public.films;
create policy "Auth write films" on public.films
for all to authenticated
using (true)
with check (true);

drop policy if exists "Auth write theatre_films" on public.theatre_films;
create policy "Auth write theatre_films" on public.theatre_films
for all to authenticated
using (true)
with check (true);

drop policy if exists "Auth write showings" on public.showings;
create policy "Auth write showings" on public.showings
for all to authenticated
using (true)
with check (true);

create or replace function public.replace_showtimes_data(payload jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  theatre_item jsonb;
  film_item jsonb;
  theatre_film_item jsonb;
  showing_item jsonb;
  theatre_id_map jsonb := '{}'::jsonb;
  film_id_map jsonb := '{}'::jsonb;
  theatre_id bigint;
  film_id bigint;
  theatre_key text;
  film_key text;
begin
  if auth.role() <> 'authenticated' then
    raise exception 'Not authorized';
  end if;

  if payload is null then
    raise exception 'Payload is required';
  end if;

  delete from public.showings where true;
  delete from public.theatre_films where true;
  delete from public.theatres where true;
  delete from public.films where true;

  for theatre_item in
    select value from jsonb_array_elements(coalesce(payload->'theatres', '[]'::jsonb))
  loop
    insert into public.theatres (name, city, address, website)
    values (
      coalesce(theatre_item->>'name', ''),
      coalesce(theatre_item->>'city', ''),
      coalesce(theatre_item->>'address', ''),
      coalesce(theatre_item->>'website', '')
    )
    returning id into theatre_id;

    theatre_key := theatre_item->>'key';
    theatre_id_map := theatre_id_map || jsonb_build_object(theatre_key, theatre_id);
  end loop;

  for film_item in
    select value from jsonb_array_elements(coalesce(payload->'films', '[]'::jsonb))
  loop
    insert into public.films (title, year, tmdb_id, ticket_link, tmdb_json)
    values (
      coalesce(film_item->>'title', ''),
      nullif(film_item->>'year', '')::integer,
      nullif(film_item->>'tmdb_id', '')::bigint,
      '',
      film_item->'tmdb_json'
    )
    returning id into film_id;

    film_key := film_item->>'key';
    film_id_map := film_id_map || jsonb_build_object(film_key, film_id);
  end loop;

  for theatre_film_item in
    select value from jsonb_array_elements(coalesce(payload->'theatre_films', '[]'::jsonb))
  loop
    theatre_id := nullif(theatre_id_map->>(theatre_film_item->>'theatre_key'), '')::bigint;
    film_id := nullif(film_id_map->>(theatre_film_item->>'film_key'), '')::bigint;

    if theatre_id is not null and film_id is not null then
      insert into public.theatre_films (theatre_id, film_id, ticket_link)
      values (theatre_id, film_id, coalesce(theatre_film_item->>'ticket_link', ''));
    end if;
  end loop;

  for showing_item in
    select value from jsonb_array_elements(coalesce(payload->'showings', '[]'::jsonb))
  loop
    theatre_id := nullif(theatre_id_map->>(showing_item->>'theatre_key'), '')::bigint;
    film_id := nullif(film_id_map->>(showing_item->>'film_key'), '')::bigint;

    if theatre_id is not null and film_id is not null then
      insert into public.showings (theatre_id, film_id, show_date, times)
      values (
        theatre_id,
        film_id,
        (showing_item->>'show_date')::date,
        array(select jsonb_array_elements_text(coalesce(showing_item->'times', '[]'::jsonb)))
      );
    end if;
  end loop;
end;
$$;

revoke all on function public.replace_showtimes_data(jsonb) from public;
grant execute on function public.replace_showtimes_data(jsonb) to authenticated;
